# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "795df4e99985f42c61ccf34678761449"
name = "proovd"
application_url = "https://proovd.in"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2024-10"

[access_scopes]
scopes = "read_products,write_products,read_customers,write_script_tags"

[auth]
redirect_urls = [
  "http://localhost:3000/api/shopify/callback",
  "http://localhost:3001/api/shopify/callback",
  "http://localhost:3002/api/shopify/callback",
  "https://proovd.in/api/shopify/callback"
]


